package com.hotel.admin.app.dto.user;


import jakarta.validation.constraints.*;
import lombok.*;
import java.util.Set;

@Getter @Setter
public class UserCreateRequest {
    @NotBlank(message = "Username is mandatory")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    private String username;

    @NotBlank(message = "Email is mandatory")
    @Email(message = "Invalid email format")
    @Size(max = 100)
    private String email;

    @NotEmpty(message = "User must have at least one role")
    private Set<String> roles; // Set of role names (e.g., "ROLE_ADMIN", "ROLE_STAFF")

    @Size(max = 100)
    private String fullName;

    @Size(max = 20)
    private String contactPhone;

    // Password generated by service
    // Status defaults to ACTIVE (or PENDING_RESET based on service logic)
    // passwordResetRequired set to true by service
}