package com.hotel.admin.app.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.hotel.admin.app.entity.enums.RoomStatus;

@Entity
@Table(name = "room")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Room {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 6) // Mandatory, unique, max length 6 (US016)
    // Note: US016 says autogenerated but also unique. Let's make it assigned via service logic.
    // US015 says non-editable. This is a business rule applied in the service/controller, not an entity constraint.
    private String roomNumber;

    @ManyToOne(fetch = FetchType.EAGER) // Eager loading for RoomType as it's essential
    @JoinColumn(name = "room_type_id", nullable = false) // Mandatory (US016)
    private RoomType roomType;

    @Column(nullable = false) // Mandatory (US016), positive value validation via bean validation/service
    private BigDecimal pricePerNight;

    @Enumerated(EnumType.STRING)
    @Column(length = 30, nullable = false)
    private RoomStatus roomStatus; // Availability status (US015, US016)

    @Column(nullable = false) // Mandatory (US016), positive integer validation via bean validation/service
    private Integer maxOccupancy;

    @Column(length = 500) // Optional, max length 500 (US016)
    private String description;

    @ManyToMany(fetch = FetchType.LAZY) // Lazy loading for amenities
    @JoinTable(name = "room_amenities", // Junction table
               joinColumns = @JoinColumn(name = "room_id"),
               inverseJoinColumns = @JoinColumn(name = "amenity_id"))
    private Set<Amenity> amenities = new HashSet<>(); // Optional (US016)
}
    // Enum for room status
  